FROM alpine
RUN apk update && \
    apk add --no-cache curl wget busybox-extras netcat-openbsd python3 py-pip bash && \
    pip install awscli && \
    apk --purge -v del py-pip && \
    hostname
CMD tail -f /dev/null
